service_name = "podbox_update"
current_version_file = "/etc/podbox_update/version.txt" 

# API Endpoints
update_check_api_url = "https://boxapi.sandpod.ir/v3/device/update" 
status_report_api_url = "https://boxapi.sandpod.ir/v3/device/status" 

# Timing
poll_interval_seconds = 300

download_base_dir = "/opt/updater_downloads" # Base for temporary download folders

decryption_key_hex = "1234567891234567891234567891234567891234567891234567891234567890"

# Update Script
update_script_name = "update.sh"

db_password = ""

device_token = ""

